<?php require 'partials/header.php'; ?>
<main>
    <div class='container'>
        <div class='row'>
            <div class='col-sm-3'>
                <ul class="nav nav-pills nav-stacked">
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?module=review&page=list">Reviews</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?module=cafe&page=list">Cafes</a>
                    </li>
<?php if (isset($_SESSION['username'])) {
    ?>
                        <li class="nav-item"> <a class="nav-link" href="index.php?module=review&page=add-edit">Add Review</a></li>
                        <li class="nav-item">
                            <a class="nav-link" href="index.php?page=detail&module=user">My Profile</a></li> 
<?php
}
if (array_key_exists('privilege', $_SESSION)) {
    if ($_SESSION['privilege'] === 'admin') {
        ?>
                            <li class="nav-item"> <a class="nav-link" href="index.php?module=user&page=list">User List</a></li>
                        <?php }
                    } ?>
                </ul>
            </div>
            <div class='col-sm-9'>
                <?php if ($flashes): ?>
                    <div id="flashes">
                        <?php foreach ($flashes as $flash): ?>
                            <h4 class="flash"><?php echo $flash; ?></h4>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?php require $template; ?>
            </div>
        </div>
    </div>
</div>
</div>     
</main>
<?php
require 'partials/footer.php';
