<?php 
require 'partials/header.php'; ?>
<main>
    <div class='container'>
        <div class='row'>
            <div class='col-sm-3'>
                <ul class="nav nav-pills nav-stacked">
                    <li class="nav-item">
                        <a class="nav-link active" href="index.php?module=review&page=list">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?module=review&page=add-edit">Review</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="index.php?module=cafe&page=list">Cafes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">My Profile</a>
                    </li>            
                    <li class="nav-item">
                        <a class="nav-link" href="#">Suburbs</a>
                    </li>
                </ul>
            </div>
            <div class='col-sm-9'>
                <p><?php require $template; ?></p>
            </div>
        </div>
    </div>
</div>
</div>     
</main>
<?php
require 'partials/footer.php';
